<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1HG8JJK" failures="1" tests="5" name="Test" time="0.11" errors="0" timestamp="2021-07-15T17:57:36 IST">
  <testcase classname="listeners.RetryFailedTests" name="test1" time="0.011"/>
  <testcase classname="listeners.RetryFailedTests" name="test2" time="0.009">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="listeners.RetryFailedTests" name="test2" time="0.004">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="listeners.RetryFailedTests" name="test2" time="0.004">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="listeners.RetryFailedTests" name="test2" time="0.006">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at listeners.RetryFailedTests.test2(RetryFailedTests.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test -->
